services:
    app:
        build: .
        ports:
            - "3004:3004"
        depends_on:
            - mysql
        environment:
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_USER=root
            - DB_PASS=password
            - DB_NAME=products_db
        restart: unless-stopped

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: products_db
        volumes:
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
